# Generated by Django 4.2.1 on 2023-07-27 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="elements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geom", models.TextField(blank=True, null=True)),
                (
                    "objectid",
                    models.BigIntegerField(blank=True, db_column="OBJECTID", null=True),
                ),
                (
                    "taluka",
                    models.CharField(
                        blank=True, db_column="Taluka", max_length=50, null=True
                    ),
                ),
                (
                    "area_in_ha",
                    models.FloatField(blank=True, db_column="Area_In_Ha", null=True),
                ),
                (
                    "village_name_census",
                    models.CharField(
                        blank=True,
                        db_column="Village_Name_Census",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "village_name_revenue",
                    models.CharField(
                        blank=True,
                        db_column="Village_Name_Revenue",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("temp", models.IntegerField(blank=True, db_column="Temp", null=True)),
                (
                    "shape_length",
                    models.FloatField(blank=True, db_column="Shape_Length", null=True),
                ),
                (
                    "shape_area",
                    models.FloatField(blank=True, db_column="Shape_Area", null=True),
                ),
            ],
            options={"db_table": " VILLAGE_BOUNDARY", "managed": False,},
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default Name", max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
