# Generated by Django 4.2.1 on 2023-06-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="India",
            fields=[
                ("OBJECTID", models.IntegerField(primary_key=True, serialize=False)),
                ("NAME_1", models.CharField(max_length=100)),
            ],
            options={"db_table": "India", "managed": False,},
        ),
    ]
