# Generated by Django 4.2.1 on 2023-06-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TCPLapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmarks",
            name="name",
            field=models.CharField(default="Default Name", max_length=255),
        ),
    ]
