# Generated by Django 4.2.1 on 2023-07-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TCPLapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="elements", table=" revenue_new",),
    ]
