# Generated by Django 4.2.1 on 2023-06-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TCPLapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TcplBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
