# Generated by Django 4.2.1 on 2023-08-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TCPLapp", "0002_alter_elements_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="elements", table=" VILLAGE_BOUNDARY",),
    ]
