# Generated by Django 4.2.1 on 2023-06-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TCPLapp", "0002_bookmarks_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmarks", name="name", field=models.CharField(max_length=255),
        ),
    ]
