# Generated by Django 4.2.1 on 2023-08-02 11:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TCPLapp", "0003_alter_elements_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Revenue1",
            fields=[
                (
                    "objectid",
                    models.BigIntegerField(
                        db_column="OBJECTID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "gut_number",
                    models.CharField(
                        blank=True, db_column="Gut_Number", max_length=50, null=True
                    ),
                ),
                (
                    "taluka",
                    models.CharField(
                        blank=True, db_column="Taluka", max_length=50, null=True
                    ),
                ),
                (
                    "area_in_ha",
                    models.FloatField(blank=True, db_column="Area_In_Ha", null=True),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, db_column="Source", max_length=200, null=True
                    ),
                ),
                (
                    "govtland_gayran_type",
                    models.CharField(
                        blank=True,
                        db_column="GovtLand_Gayran_Type",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "govt_private_forest_type",
                    models.CharField(
                        blank=True,
                        db_column="Govt_Private_Forest_Type",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "govtland_forest_7_12_availibility",
                    models.CharField(
                        blank=True,
                        db_column="GovtLand_Forest_7_12_Availibility",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "govtland_forest_as_7_12_full_part",
                    models.CharField(
                        blank=True,
                        db_column="GovtLand_Forest_as_7_12_Full_Part",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "old_gut_no",
                    models.CharField(
                        blank=True, db_column="Old_Gut_No", max_length=50, null=True
                    ),
                ),
                (
                    "new_gut_no",
                    models.CharField(
                        blank=True, db_column="New_Gut_No", max_length=50, null=True
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, db_column="Remark", max_length=100, null=True
                    ),
                ),
                (
                    "village_name_census",
                    models.CharField(
                        blank=True,
                        db_column="Village_Name_Census",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "village_name_revenue",
                    models.CharField(
                        blank=True,
                        db_column="Village_Name_Revenue",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("temp", models.IntegerField(blank=True, db_column="Temp", null=True)),
                (
                    "shape_length",
                    models.FloatField(blank=True, db_column="Shape_Length", null=True),
                ),
                (
                    "shape_area",
                    models.FloatField(blank=True, db_column="Shape_Area", null=True),
                ),
                (
                    "village_taluka",
                    models.CharField(
                        blank=True,
                        db_column="Village_Taluka",
                        max_length=5000,
                        null=True,
                    ),
                ),
            ],
            options={"db_table": "revenue1", "managed": False,},
        ),
    ]
