# Generated by Django 4.2.1 on 2023-08-03 05:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TCPLapp", "0004_revenue1"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalPlu",
            fields=[
                ("fid", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "taluka",
                    models.CharField(
                        blank=True, db_column="TALUKA", max_length=50, null=True
                    ),
                ),
                (
                    "broad_lu",
                    models.CharField(
                        blank=True, db_column="Broad_LU", max_length=50, null=True
                    ),
                ),
                (
                    "detailed_l",
                    models.CharField(
                        blank=True, db_column="Detailed_L", max_length=50, null=True
                    ),
                ),
                (
                    "descriptio",
                    models.CharField(
                        blank=True, db_column="Descriptio", max_length=150, null=True
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, db_column="Label", max_length=50, null=True
                    ),
                ),
                (
                    "area_ha",
                    models.FloatField(blank=True, db_column="Area_HA", null=True),
                ),
                (
                    "plu_zone",
                    models.CharField(
                        blank=True, db_column="PLU_Zone", max_length=100, null=True
                    ),
                ),
                (
                    "reservatio",
                    models.CharField(
                        blank=True, db_column="Reservatio", max_length=50, null=True
                    ),
                ),
                (
                    "pa_name",
                    models.CharField(
                        blank=True, db_column="PA_Name", max_length=50, null=True
                    ),
                ),
                (
                    "growth_centre",
                    models.CharField(
                        blank=True, db_column="Growth_Centre", max_length=100, null=True
                    ),
                ),
                (
                    "shape_length",
                    models.FloatField(blank=True, db_column="Shape_Length", null=True),
                ),
                (
                    "shape_area",
                    models.FloatField(blank=True, db_column="Shape_Area", null=True),
                ),
            ],
            options={"db_table": "Final_PLU", "managed": False,},
        ),
    ]
